name: Playwright Tests

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Instalar Playwright
        run: npx playwright install --with-deps

      - name: Executar testes
        run: npx playwright test

      - name: Salvar Relatórios
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
