name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 */6 * * *' # Executa a cada 6 horas

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache de dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar dependências
        run: npm ci

      - name: Instalar Playwright com dependências
        run: npx playwright install --with-deps

      - name: Executar testes e gerar relatórios
        run: |
          npx playwright test --reporter=html,junit

      - name: Upload do relatório HTML
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/

      - name: Upload do relatório XML
        uses: actions/upload-artifact@v4
        with:
          name: playwright-junit-report
          path: playwright-report/results.xml